services:
  app:
    #restart: always
    build: .
    ports:
      - "8501:8501"
    container_name: "rag-langchain"
    volumes:
      - ./chroma-db:/usr/src/app/chromadb
    tty: true
    depends_on:
      - db
    networks:
      - rag-network

  db:
    restart: always
    image: chromadb/chroma:0.4.24
    container_name: "chromadb-langchain"
    ports:
      - 8001:8000
    #command: run --host 0.0.0.0 --port 8000
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge